spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "${USERNAME}"
    password: "${PASSWORD}"
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
    name: back-end
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

mail:
  api:
    key: ${BREVO_API_KEY}
brevo:
  mail:
    url: ${BREVO_URL}

